/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { HouseAd } from './types';

export const INITIAL_ADS: HouseAd[] = [
  {
    id: '1',
    title: 'Casa para Alugar em Centro',
    price: 1200,
    description: 'Imóvel disponível para locação mensal em Centro, Parnaíba - PI. O imóvel conta com garagem, pet friendly. Excelente ventilação, com portas e janelas amplas, quintal espaçoso e sala de estar agradável.',
    bairro: 'Centro Histórico',
    bedrooms: 3,
    bathrooms: 1,
    area: 120,
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=600',
    whatsapp: '86999887766',
    createdAt: '2026-05-28T10:00:00.000Z',
    tipoLocacao: 'Mensal',
    anunciante: 'Particular',
    nomeContato: 'Mariano Lopes',
    enderecoCompleto: 'Rua Pedro II, Centro',
    numeroCasa: '412',
    showExactAddress: true,
    garage: 'Sim',
    garageCount: 1,
    salas: 1,
    cozinhas: 1,
    petFriendly: true
  },
  {
    id: '2',
    title: 'Casa de Temporada com Piscina no Planalto',
    price: 350,
    description: 'Linda casa de veraneio mobiliada com piscina refrescante de cascata, deck de churrasqueira, teto alto com excelente circulação de ar, ar condicionado nos quartos e área de lazer privativa completa em bairro tranquilo de Parnaíba.',
    bairro: 'Planalto',
    bedrooms: 2,
    bathrooms: 2,
    area: 160,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600',
    whatsapp: '86994553322',
    createdAt: '2026-05-29T14:30:00.000Z',
    tipoLocacao: 'Temporada',
    anunciante: 'Particular',
    nomeContato: 'Dona Socorro',
    enderecoCompleto: 'Rua das Palmeiras, Planalto',
    numeroCasa: '1240',
    showExactAddress: false,
    garage: 'Sim',
    garageCount: 2,
    salas: 2,
    cozinhas: 1,
    petFriendly: true
  },
  {
    id: '3',
    title: 'Sobrado Duplex Moderno no Reis Veloso',
    price: 2200,
    description: 'Excelente duplex com fino acabamento em porcelanato próximo à UFDPar. Aluguel mensal para famílias ou estudantes. Cozinha americana integrada, vaga de garagem, suítes modernas no piso superior e área de serviço separada.',
    bairro: 'Reis Veloso',
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600',
    whatsapp: '86998114422',
    createdAt: '2026-05-30T09:15:00.000Z',
    tipoLocacao: 'Mensal',
    anunciante: 'Imobiliária',
    nomeContato: 'Parnaíba Imóveis Ltda',
    enderecoCompleto: 'Avenida São Sebastião',
    numeroCasa: '2800',
    showExactAddress: true,
    garage: 'Sim',
    garageCount: 2,
    salas: 1,
    cozinhas: 1,
    petFriendly: false
  },
  {
    id: '4',
    title: 'Chalé Maravilhoso na Praia do Coqueiro',
    price: 550,
    description: 'Aconchegante chalé com estilo rústico caiçara na Praia do Coqueiro. Ideal para praticantes de kitesurf e veranistas de férias. Varanda imensa em L com ganchos de rede, estacionamento amplo e quintal gramado.',
    bairro: 'Coqueiro',
    bedrooms: 3,
    bathrooms: 3,
    area: 210,
    imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80&w=600',
    whatsapp: '86999123456',
    createdAt: '2026-05-25T11:00:00.000Z',
    tipoLocacao: 'Temporada',
    anunciante: 'Particular',
    nomeContato: 'Carlos Kite',
    enderecoCompleto: 'Beira Mar, Coqueiro',
    numeroCasa: 'S/N',
    showExactAddress: true,
    garage: 'Sim',
    garageCount: 3,
    salas: 1,
    cozinhas: 2,
    petFriendly: true
  }
];
